### ISSUE TITLE
Bucket resource is missing

### ISSUE THREAD

**Issue by seuros** [contabo/terraform-provider-contabo#10]
Hi again

Is there a way to generate a bucket resource currently ?

**Comment by tahergalal** [comment]
currently not this is under development will inform you as soon as it is available

**Comment by ngotzmann** [comment]
The bucket resource was added in our last version 0.1.17, you can see it [here](https://registry.terraform.io/providers/contabo/contabo/latest/docs/resources/contabo_object_storage_bucket).
