### ISSUE TITLE
contabo_instance display_name revert remotely after 24h.

### ISSUE THREAD

**Issue by seuros** [contabo/terraform-provider-contabo#11]
```
resource "contabo_instance" "test_server_eu" {
  display_name = "Terraform Server EU"
}
`````
"Seuros Testing"  =>  "Terraform Server EU"

After 24h the state reset to the initial display name which seem like a drift.

**Comment by tahergalal** [comment]
Sorry for this we are working on fixing this issue in the meantime

**Comment by tahergalal** [comment]
should be working now can you please test again the name will not be reverted back again

**Comment by seuros** [comment]
Seem it was fixed correctly. Thanks.
