### ISSUE TITLE
Document or add feature to modify existing instance

### ISSUE THREAD

**Issue by loic-roux-404** [contabo/terraform-provider-contabo#14]
I have tried two time terraform provider with this config : 

```tf
resource "contabo_instance" "paas_instance" {
  #image_id = contabo_image.paas_instance.id
  ssh_keys = [contabo_secret.paas_instance_ssh_key.id]
  user_data = templatefile(
    "${path.module}/cloud-init.yaml",
    {
      ansible_vars = local.ansible_vars
    }
  )
}

```

I think providing an instance id to resource should be an option to avoid ordering a new VPS.

Is there any feature to update existing instance and perform os reinstalls ? I have ordered two instance for my tests and i'm tired of emailing your support for stoping theses unwanted subscriptions...

**Comment by Dirnei** [comment]
Not sure if you allready know it, but when you declare a new ressoruce that allready exists, but not in your tf state, you could import it with: `terraform import contabo_instance.paas_instace 999932168`
You can get the id via the contabo cli

And I agree, when you change something in your cloudinit config it forces a reinstall of the os

**Comment by loic-roux-404** [comment]
> Not sure if you allready know it, but when you declare a new ressoruce that allready exists, but not in your tf state, you could import it with: `terraform import contabo_instance.paas_instace 999932168` You can get the id via the contabo cli
> 
> And I agree, when you change something in your cloudinit config it forces a reinstall of the os

Thanks thats what i was researching

But is it even documented ?

Also, why not adding the feature to do it in the `contabo_instance` ?

**Comment by loic-roux-404** [comment]
Opened #19 to add terraform import behaviour directly in the module and avoid unwanted subscription and payments.

**Comment by ngotzmann** [comment]
Merged your pull request, it is availabe with the provider version https://registry.terraform.io/providers/contabo/contabo/0.1.20.
Thank you!
