### ISSUE TITLE
DataSource contabo_secret value required

### ISSUE THREAD

**Issue by Dirnei** [contabo/terraform-provider-contabo#15]
Hi!

i wanted to reuse the ssh key and the root password, defined in an other repository, so i wanted to retrieve it via the data source.
Maybe i don't get it, but why is the `value` required?

---

**Update 1**

When i set all values like in the resource (name, type, value) and let it run i get the error:

> API error, status code: 404, details: Entry Secret not found by secretId = 0

---

**Update 2**

When i change the cloudinit config, which forces a reinstall, the password/ssh_key i defined in the resource, is not set again. It only work when i create a new contabo_secret.
I guess there is a bigger problem on the hole contabo_secret?

---
Thanks in advance,
Chris

**Comment by ngotzmann** [comment]
The datasource is fixed in version https://registry.terraform.io/providers/contabo/contabo/0.1.20

Thanks for reporting!
