### ISSUE TITLE
"display_name" argument does not work

### ISSUE THREAD

**Issue by dnssmr** [contabo/terraform-provider-contabo#16]
Hi!
The Documentation specifies "display_name" as an optional argument for the object_storage resource.  
However, when trying to create an object storage with a display name, terraform says it's an unsupported argument.

```
│ Error: Unsupported argument
│ 
│   on main.tf line 59, in resource "contabo_object_storage" "xxx_object_storage":
│   59:         display_name              = var.object_storage_display_name
│ 
│ An argument named "display_name" is not expected here.
```

I can provide more info if needed.
Thank you!

**Comment by ngotzmann** [comment]
Thanks for reporting!
Everything is fixed in the newest version: https://registry.terraform.io/providers/contabo/contabo/0.1.20
