### ISSUE TITLE
Error 500 on instance creation. Unable to create server.

### ISSUE THREAD

**Issue by gaugau3000** [contabo/terraform-provider-contabo#17]
When using terraform apply, I got this error (terraform validate has been done previous and is valid)

╷
│ Error: API error, status code: 500
│ 
│   with contabo_instance.bybit_bots,
│   on main.tf line 19, in resource "contabo_instance" "bybit_bots":
│   19: resource "contabo_instance" "bybit_bots" {
│ 
│ API error, status code: 500, details: Internal Server Error, retry or contact support

below config to reproduce :

resource "contabo_instance" "bybit_bots" {
  image_id      = "afecbb85-e2fc-46f0-9684-b46b1faf00bb"
  display_name  = "worker-8"
  product_id    = "V14"
  region        = "SIN"
  period        = 1
  root_password = 1289465213897
}

Have a nice day.

**Comment by pascalski** [comment]
Got the same issue with my new contabo account. Can somebody look into this?

**Comment by tahergalal** [comment]
@gaugau3000 Sorry for the late reply. After checking the above config the provided root_password is incorrect causing the issue. This is basically why you are getting the error for the above configuration I hope this help.

**Comment by gaugau3000** [comment]
What you mean by incorrect (of course I have not provided the good password in GitHub) → missing quotes....?
What is the probability that @pascalski and I enter the wrong password ?

Many tks

**Comment by pascalski** [comment]
In my case i was billed for those API Calls and the Support did not help in any was. This means the API Key was correct.

At this point i wasted around 50 bucks in resources for trying to use your Terraform Provider and contabo Support did not even care to fix the issue. Your Provider is broken.

**Comment by gaugau3000** [comment]
Tks for input, contabo are the maintainers (on terraform from what I see) and didn't fix it and don't refund... well, well.

**Comment by pascalski** [comment]
@gaugau3000 i will stick with other providers from hetzner etc from now on. Thought i would test contabo because of the pricing, but it is not worth the headache

**Comment by tahergalal** [comment]
> What you mean by incorrect (of course I have not provided the good password in GitHub) → missing quotes....? What is the probability that @pascalski and I enter the wrong password ?
> 
> Many tks

@gaugau3000 Both issues are different.

I am sure you did not provide the actual password. I am talking about the configuration provided above. There is a root_password. You provided 1289465213897, this is basically a wrong value which was causing the issues if you want to use root_password please check out [Secret API](https://api.contabo.com/#tag/Secrets/operation/retrieveSecretList)

After creating the password and securely storing it you can then use the Id for the root_password parameter. 

I can assure you that in your Case there was no VPS Created in SIN with the terraform provider. Would gladly help you further if you are still facing issues using the terraform provider.

**Comment by tahergalal** [comment]
> @gaugau3000 i will stick with other providers from hetzner etc from now on. Thought i would test contabo because of the pricing, but it is not worth the headache

The support of Contabo have tried reaching out to you on 21.07.2023 and got no answer from your side to try to help you.  We are trying to work on mitigating any issues that you may have faced using the Terraform provider.
