### ISSUE TITLE
Instance add-on doesn't work

### ISSUE THREAD

**Issue by alex3498** [contabo/terraform-provider-contabo#2]
I've created a new instance using a config like this:
```terraform
resource "contabo_instance" "main" {
  region       = "EU"
  period       = 1
  product_id = "V3" // VPS L
  ssh_keys   = var.keys
  user_data  = templatefile("${path.module}/../user_data/server.yaml", {})
  # https://contabo.com/en/product-list/?show_ids=true
  add_ons {
    id       = "1474"
    quantity = 1
  }
}
```
1474 - add on id for additional SSD storage

After the instance creation, it didn't have the additional storage.

Also, it doesn't seem that user_data was applied as well. Not sure how to double check that.

**Comment by alex3498** [comment]
I've added storage through the web UI. However, on the next `terraform plan`, it crashed during the refresh step

```
╷
│ Error: add_ons.0.id: '' expected type 'string', got unconvertible type 'int64', value: '1474'
│ 
│   with module.server.contabo_instance.main,
│   on server/instances.tf line 4, in resource "contabo_instance" "main":
│    4: resource "contabo_instance" "main" {
│ 
╵
```

**Comment by tahergalal** [comment]
Thanks for pointing out the bug. We will fix the issue that you are currently having with the sync.

With regards to the issue with buying the addons, this is currently not possible using terraform we will be adding more features as we go but for the time you can only buy the main product.

**Comment by tahergalal** [comment]
Hi The new version 0.1.12 has already the problem of loading addons fixed please use it
