### ISSUE TITLE
Improve documentation how to get IDs i.e. "object_storage_id"

### ISSUE THREAD

**Issue by mrclrchtr** [contabo/terraform-provider-contabo#21]
It's really difficult to find out, what the correct "object_storage_id" is to create an object storage bucket. I hat to debug the web interface and analyze the json response from the server with the chrome developer utils to get the ID ;)

**Comment by ngotzmann** [comment]
Sorry for the struggle...
I added documentation on the contabo_object_storage_bucket resource in the latest version v0.1.22.
https://registry.terraform.io/providers/contabo/contabo/0.1.22
