### ISSUE TITLE
Resource to manage tags

### ISSUE THREAD

**Issue by ngotzmann** [contabo/terraform-provider-contabo#23]
On the contabo api there is a feature to add tags to the offered products, like instances and object-storages.
As I can see this feature is missing from the terraform provider, it would be very nice to directly add tags to my instances on provision via terraform, else I have to call the api seperatly and this breaks my automation workflow.

I would appreciate to have this feature.

**Comment by dnssmr** [comment]
I would also like to have this feature. Would help greatly with my automation.

**Comment by ziermach** [comment]
would be great

**Comment by RincewindsHat** [comment]
this would indeed be very useful
