### ISSUE TITLE
Error 500 while creating object storage

### ISSUE THREAD

**Issue by marcospastor** [contabo/terraform-provider-contabo#27]
Hi, new Contabo account. Tried to create an object storage resource using Terraform.

I get this error:

```
Error: API error, status code: 500

  with contabo_object_storage.storage_eu,
  on main.tf line 4, in resource "contabo_object_storage" "storage_eu":
   4: resource "contabo_object_storage" "storage_eu" {

API error, status code: 500, details: Internal Server Error, retry or contact support
```

I have provided credentials in this block (using variables)

```
provider "contabo" {
  oauth2_client_id     = "${var.contabo_clientid}"
  oauth2_client_secret = "${var.contabo_clientsecret}"
  oauth2_user          = "${var.contabo_username}"
  oauth2_pass          = "${var.contabo_password}"
}
```

I have tested these values with Contabo client API and seems working.

What could be the reason?

Thanks!

Marcos

**Comment by arcus-ops** [comment]
Hi,
I found your support ticket.
Can you please create a new customer account and if you still have issues for what ever reasons please reach out to the customer support again.
