### ISSUE TITLE
Update Contabo API with the updated offers (V51 etc...) on the Terraform Provider Registry

### ISSUE THREAD

**Issue by HugoBroudeur** [contabo/terraform-provider-contabo#29]
The latest provider registry was uploaded 3 months ago on the Terraform Provider Registry:
https://registry.terraform.io/providers/contabo/contabo/latest

The image was built at that time with the API schema from 3 months ago.
Contabo has updated its offers (https://api.contabo.com/#tag/Instances/operation/createInstance), deprecated many of its products and added new ones.

In the current version, if I try to create a new instance using a V51 product, the Contabo terraform provider returns an error 400 because its internal client API generated in the `make build` step is outdated and does not exist.

After further tests, that's not the reason.

`main.tf`
```
# Create a new secret
resource "contabo_secret" "sshkey" {
  name  = var.UUID
  type  = "ssh"
  value = var.PUBLIC_KEY
}

resource "contabo_instance" "validator" {
  display_name = var.UUID
  image_id     = var.IMAGE_ID # Default image
  product_id   = "V51"
  region       = "US-west"
  ssh_keys     = [contabo_secret.sshkey.id]
  period       = 1
  add_ons {
    id       = "1629" # addon ID for location US-west
    quantity = 1
  }
}

```

Outputs in a gitlab runner to provision the Contabo instance. 
`gitlab-terraform check` returns the following success:
```
Terraform has been successfully initialized!
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create
Terraform will perform the following actions:
  # contabo_instance.validator will be created
  + resource "contabo_instance" "validator" {
      + additional_ips       = (known after apply)
      + cpu_cores            = (known after apply)
      + created_date         = (known after apply)
      + disk_mb              = (known after apply)
      + display_name         = "some_name"
      + error_message        = (known after apply)
      + existing_instance_id = (known after apply)
      + id                   = (known after apply)
      + image_id             = "some_image_id"
      + ip_config            = (known after apply)
      + last_updated         = (known after apply)
      + license              = (known after apply)
      + mac_address          = (known after apply)
      + name                 = (known after apply)
      + os_type              = (known after apply)
      + period               = 1
      + product_id           = "V51"
      + product_type         = (known after apply)
      + ram_mb               = (known after apply)
      + region               = "US-west"
      + ssh_keys             = (known after apply)
      + status               = (known after apply)
      + v_host_id            = (known after apply)
      + add_ons {
          + id       = "1629"
          + quantity = 1
        }
    }
```

`gitlab-terraform apply` returns the following error
```
Terraform has been successfully initialized!
contabo_secret.sshkey: Creating...
contabo_secret.sshkey: Creation complete after 1s [id=84623]
contabo_instance.validator: Creating...
╷
│ Error: API error, status code: 400
│ 
│   with contabo_instance.validator,
│   on main.tf line 8, in resource "contabo_instance" "validator":
│    8: resource "contabo_instance" "validator" {
│ 
│ API error, status code: 400, details: Bad Request Invalid location addon
```

The tests I have done are the following:
in `main.tf` I have added/removed the `add_ons` list from the configuration: no effect.
I have forked this repository, rebuilt it to get the latest API schema and republished it: https://registry.terraform.io/providers/HugoBroudeur/contabo/latest
It's still the same error.

At this point I have no idea what is happening, it looks similar to a resolved issue: https://github.com/contabo/terraform-provider-contabo/issues/12

What I try to achieve:
create an instance using the product "V51" and deploy it in "US-west"

After another test, the same issue happens for the product "V45" and the region "AUS"

**It works for the product "V48" and the region "EU"**

**Comment by abdelann** [comment]
Hi there, 
 it seems like a config issue, from our side it was tested and it works with V51. We will close this ticket, please create a customer ticket and mention this Github issue so we can follow up if the issue persists on your side. Thanks
