### ISSUE TITLE
Add a way to retrieve object storage by name

### ISSUE THREAD

**Issue by luis-guimaraes-exoawk** [contabo/terraform-provider-contabo#30]
Could we have a way to retrieve an object storage by using it's name?
It would make the `object_storage` datasource more useful than having to find the `objectStorageId` through the API.

Thanks

**Comment by abdelann** [comment]
the LIST API is for search purposes where you can pass a name, not to get one single element, not like GET Api /objectStorageId that will always gives 1 element or none.
