### ISSUE TITLE
data source contabo_secret should be able to find the secret by name

### ISSUE THREAD

**Issue by l-with** [contabo/terraform-provider-contabo#35]
The name attribute of resource contabo_secret has to be unique. The usage of the data source is to use a secret deployed by another terraform project (especially for ssh keys). It should be possible to select the secret by the name. The [api](https://api.contabo.com/#tag/Secrets/operation/retrieveSecretList) has a query parameter name.

**Comment by abdelann** [comment]
the LIST API is for search purposes, not to get one single element, not like GET Api /secretId
