### ISSUE TITLE
The description of display_name in the documentation is wrong

### ISSUE THREAD

**Issue by jorgepsmatos** [contabo/terraform-provider-contabo#4]
On the following documentation file `/docs/resources/contabo_instance.md` the description for `display_name` is the same as for  `image_id` which I think is not correct.

This can also be seen here https://registry.terraform.io/providers/contabo/contabo/latest/docs/resources/contabo_instance#display_name

**Comment by ngotzmann** [comment]
Sorry, we should be more careful with copy paste... :)
Its fixed in version [0.1.14](https://registry.terraform.io/providers/contabo/contabo/0.1.14).

And thanks for notifying us!
