### ISSUE TITLE
Can i create multiple instance with same name as "instance1" ?

### ISSUE THREAD

**Issue by anildalar** [contabo/terraform-provider-contabo#40]
resource "contabo_instance" "instance1" {
  product_id    = "V2"
  region        = "EU"
  period        = 3 
}

**Comment by tahergalal** [comment]
you can always use the count meta of terraform so in the example above you would change to the following to order 3 instances

resource "contabo_instance" "instance1" {
count = 3 
product_id = "V2"
region = "EU"
period = 3
}
