### ISSUE TITLE
Issue: Intermittent API Error with Contabo Terraform Provider for Instance creation

### ISSUE THREAD

**Issue by ehtishammubarik** [contabo/terraform-provider-contabo#42]
#### Description
I'm encountering an intermittent issue while creating instances with the Contabo Terraform provider. The provider successfully creates instances on Contabo most of the time, but occasionally it generates an error message with `status code: 0`. Here’s the error output:

```
│ Error: API error, status code: 0
│ 
│   with contabo_instance.contabo-tf-master[0],
│   on contabo.tf line 7, in resource "contabo_instance" "contabo-tf-master":
│    7: resource "contabo_instance" "contabo-tf-master" {
│ 
│ API error, status code: 0, details: 
```

The instance is created successfully, and I can access it, but Terraform ends with this error, preventing a clean apply or destroy workflow. It is not clear why the API returns status code `0`, and there are no further details in the error output.

The issue appears randomly—sometimes the `terraform apply` completes without any errors, while other times I get the error mentioned above.

#### Affected Configuration
Here’s a portion of my Terraform configuration for the Contabo provider:

```hcl
resource "contabo_instance" "contabo-tf-master" {
  display_name = "${var.project_name}-cb-m"
  count        = var.contabo_instance_count >= 1 ? 1 : 0
  product_id   = "V48" 
  region       = "EU"
  period       = 1
  image_id     = "afecbb85-e2fc-46f0-9684-b46b1faf00bb" 
  ssh_keys     = [contabo_secret.ssh_key.id] 
  user_data    = ...
}

provider "contabo" {
  oauth2_client_id     = var.contabo_client_id
  oauth2_client_secret = var.contabo_client_secret
  oauth2_user          = var.contabo_user
  oauth2_pass          = var.contabo_pass
}

terraform {
  required_providers {
    contabo = {
      source  = "contabo/contabo"
      version = ">= 0.1.26"
    }
  }
}
```

#### Steps to Reproduce
1. Run `terraform apply` using the above configuration.
2. Observe that the instance gets created successfully in Contabo.
3. Note that sometimes Terraform returns an API error with `status code: 0`, even though the instance appears to be created successfully.

#### Expected Behavior
The instance should be created successfully without any API error, and `terraform apply` should complete without errors.

#### Actual Behavior
Terraform creates the instance, but intermittently ends with an API error (`status code: 0`), which results in an incomplete apply status.

#### Environment
- **Provider Version**: `contabo/contabo >= 0.1.26`
- **Terraform Version**: `>= 1.0`
- **Contabo Product ID**: `V48`
- **Region**: `EU`

#### Additional Information
- This issue occurs randomly. There are times when everything works correctly, and there are no errors during `terraform apply`.
- The randomness of the issue makes it challenging to debug and maintain a clean workflow for applying and destroying instances because Terraform doesn’t register the instance as successfully created when the error occurs. This also impacts subsequent resource dependencies and automation.

I would appreciate any guidance on how to troubleshoot or resolve this intermittent error.

Thank you for your support.

**Comment by abdelann** [comment]
the issue is resolved

**Comment by ehtishammubarik** [comment]
@abdelann  RELEASE action failed, can you please check & trigger the release properly for newer version ? 

https://github.com/contabo/terraform-provider-contabo/actions/runs/11707345564/job/32606512279

**Comment by ehtishammubarik** [comment]
> the issue is resolved

Not fixed yet.

**Comment by abdelann** [comment]
0.1.27 is now released, sorry for any inconvenience.
