### ISSUE TITLE
Cannot get the private IP from an instance

### ISSUE THREAD

**Issue by jorgepsmatos** [contabo/terraform-provider-contabo#6]
For my specific use case, I need to know the private network IPs of my instances.

But neither the `contabo_instance` nor `contabo_private_network` return the private IP.

In the case of `contabo_instance`, on the `ip_config` I only get the public IPs (same when using the API)

In the case of `contabo_private_network`, I get an array with `instance_ids`, but not private IP of each of them:

```
instance_ids  = [
          20100*****,
          20100*****,
        ]
```

This is contrary to the API, where I can see the private IPs of the instances on `data[*].instances[*].privateIpConfig.v4[*].ip`

**Comment by Maximilian-Temeschinko** [comment]
Hello [jorgepsmatos](https://github.com/jorgepsmatos),

you are right, we need at least one place where the private IP addresses are listed. We will add it to the `contabo_private_network`'s `instances` list as it is in the API spec.

Thank you for finding it.

**Comment by Maximilian-Temeschinko** [comment]
Sorry for the delay. Instances (with their private ip addresses) are now listed in the `contabo_private_network` resource.
Please check out version `0.1.15`
