### ISSUE TITLE
Changing the display_name of a server, cause it to reset.

### ISSUE THREAD

**Issue by seuros** [contabo/terraform-provider-contabo#9]
Hi

I wanted to change the display name of one of my servers and  the plan was showing a in-place change.

The whole server was reset to it factory default.

The display name didnt change.

**Comment by ngotzmann** [comment]
We are very sorry for this bug. This should'nt happen again.
We added documentation that changing image_id, user_data, ssh_keys and root_password will reinstall your server.
Changing the display_name is now working and not more reinstalling the server... 

The changes are in the newest version [0.1.16](https://registry.terraform.io/providers/contabo/contabo/0.1.16).
